### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by niklasvm** [niklasvm/shiny-strava#2]
App gives an error during authentication

**Comment by niklasvm** [comment]
I've pushed some changes and updated the readme. It should work now

**Comment by fawda123** [comment]
Just pinging myself here so I get email updates on this issue...

**Comment by fawda123** [comment]
@niklasvm This might be from my own stupidity but I can't get the app to authenticate on my account.  I've followed the steps in the README file but get an error in my browser when I try to authenticate:

```
{"message":"Bad Request","errors":[{"resource":"Application","field":"client_id","code":"invalid"}]}
```

My `.Rprofile` file looks like this (with relevant info x'ed out):

```
strava_app_name <- 'xxxx'
strava_app_client_id <- 'xxxx'
strava_app_secret <- 'xxxx'
```
I didn't include the `strava_app_url` because I assumed it is redirected to ` strava_app_url = glue("http://192.168.99.100:8787/p/6365/")` in the `global.R` file.  I also remembered that this isn't required to authenticate in rStrava.  Any ideas?

**Comment by niklasvm** [comment]
You will need to specify the **strava_app_url** exactly like it appears when you click run app: 

![image](https://user-images.githubusercontent.com/18314300/42136969-ac5c9d4c-7d64-11e8-8afb-ff8b2e070bf7.png).

The other variables need to be set as environment variables:

```{r}
Sys.setenv(
  strava_app_name='Shiny Strava',
  strava_app_url = 'xxxxxx',
  strava_app_client_id  = xxxx,
  strava_app_secret = 'xxxx'
)
````

I've just pushed a change to make it a bit clearer in the global.R file.

**Comment by niklasvm** [comment]
Once its working correctly your activities will download into a data table and be displayed:
![image](https://user-images.githubusercontent.com/18314300/42137087-9d86a98c-7d66-11e8-9a02-7ff126702887.png)

**Comment by fawda123** [comment]
Perfect, that worked!  I made some minor edits to the readme and removed the .Rprofile source in the global file.  Looks like .Rprofile isn't needed anymore.  

Is the plan now to start adding some plotting functionality?  

#3

**Comment by niklasvm** [comment]
Thanks for those changes. That's correct. I'll look at setting up a basic layout with some heatmap charts

**Comment by niklasvm** [comment]
@fawda123 I'm going to close this. When I push new changes I'll add you as a reviewer
