### ISSUE TITLE
Update to look and feel and a first stab at the heatmap

### ISSUE THREAD

**Issue by niklasvm** [niklasvm/shiny-strava#5]
Hey @fawda123

I have created a development branch where I have changed up the look and feel of the app (added the strava buttons, etc).

I have also added some controls to draw a heat map based on date range, type and city (although it seems city has been discontinued).

Please would you give it a test?

**Comment by fawda123** [comment]
Hey @niklasvm, seems to work okay for me, but yea it's a shame the city info isn't there.  Otherwise, the only issue I can see in the current app is the scaling on ggmap for the heatmap - it would be better to do this with leaflet and it looks like you're on it already.  

Also, would it be feasible to have some input boxes on the app for the user login info?  It would be nice not to mess with this in the global.R file and enter directly within the app itself.  I guess there are some drawbacks to this, i.e., having that info displayed on the app rather than under the hood.  Anyway, I took a stab at it in my commit 86c89849f382d9ec2436f9260953b3dcccdd5c8b I've also opened a separate issue if you want to pursue this.
